name: AutoMoney V28 Run

on:
  schedule:
    - cron: '30 */6 * * *' # 每 6 小時執行一次
  workflow_dispatch:      # 允許手動按鈕觸發

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 賦予寫入權限 (為了更新 history.txt)
    
    steps:
      - name: 1. 下載程式碼
        uses: actions/checkout@v3

      - name: 2. 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. 安裝套件
        run: pip install -r requirements.txt

      - name: 4. 執行機器人
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
          WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
        # ↓↓↓ 修正重點：run 必須跟上面的 env 對齊 (往左靠) ↓↓↓
        run: python bot_code.py

      - name: 5. 儲存記憶
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@noreply.github.com"
          git add history.txt
          # 如果沒有更新就不報錯，有更新就存檔
          git diff --quiet && git diff --staged --quiet || (git commit -m "Log Update" && git push)
